export const MOVIES = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "The Lord of the Rings: The Return of the King",
  "Schindler's List",
  "Fight Club",
  "Forrest Gump",
  "Inception",
  "Star Wars: Episode V - The Empire Strikes Back",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Matrix",
  "Goodfellas",
  "One Flew Over the Cuckoo's Nest",
  "Seven Samurai",
  "Star Wars: Episode IV - A New Hope",
  "City of God",
  "Se7en",
  "The Silence of the Lambs",
  "It's a Wonderful Life",
  "Life Is Beautiful",
  "The Usual Suspects",
  "The Lion King",
  "Back to the Future",
  "Pulp Fiction",
  "Gladiator",
  "Whiplash",
  "The Prestige",
  "The Green Mile",
  "Interstellar",
  "The Intouchables",
  "The Pianist",
  "The Terminator",
  "The Good, the Bad and the Ugly",
  "The Social Network",
  "Saving Private Ryan",
  "American History X",
  "The Shining",
  "12 Angry Men",
  "The Great Escape",
  "Casablanca",
  "Citizen Kane",
  "Gone with the Wind",
  "The Bridge on the River Kwai",
  "A Clockwork Orange",
  "Pulp Fiction",
  "The Revenant",
  "Star Wars: Episode VI - Return of the Jedi",
  "The Big Lebowski",
  "The Wizard of Oz",
  "The Maltese Falcon",
  "The French Connection",
  "To Kill a Mockingbird",
  "Lawrence of Arabia",
  "Amadeus",
  "Blade Runner 2049",
  "Inglourious Basterds",
  "Parasite",
  "The Hunt",
  "Requiem for a Dream",
  "Memento",
  "Jaws",
  "Apocalypse Now",
  "Heat",
  "The Thing",
  "The Matrix Reloaded",
  "The Matrix Revolutions",
  "Mad Max: Fury Road",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "The Sixth Sense",
  "The Big Short",
  "The Truman Show",
  "The Dark Knight Rises",
  "The Big Lebowski",
  "The Godfather Part III",
  "A Beautiful Mind",
  "The King's Speech",
  "A Few Good Men",
  "Catch Me If You Can",
  "The Grand Budapest Hotel",
  "The Departed",
  "Scream",
  "The Shape of Water",
  "The Hunger Games",
  "The Iron Giant",
  "The Hobbit: An Unexpected Journey",
  "Spider-Man: Into the Spider-Verse",
  "Guardians of the Galaxy",
  "Black Panther",
  "Toy Story",
  "Shutter Island",
  "Deadpool",
  "Frozen",
  "The Lego Movie",
  "The Incredibles",
  "The Avengers",
  "Iron Man",
  "Spider-Man 2",
  "Avengers: Endgame",
  "Ender's Game",
  "The Lord of the Rings: The Two Towers",
  "Guardians of the Galaxy Vol. 2",
  "The Godfather Part II",
  "A Quiet Place",
  "Her",
  "Lady Bird",
  "Mad Max: Fury Road",
  "Moonlight",
];
