/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoggedInLayoutRouteImport } from './routes/_loggedInLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoggedInLayoutServerIdIndexRouteImport } from './routes/_loggedInLayout/$serverId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedInLayoutRoute = LoggedInLayoutRouteImport.update({
  id: '/_loggedInLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedInLayoutServerIdIndexRoute =
  LoggedInLayoutServerIdIndexRouteImport.update({
    id: '/$serverId/',
    path: '/$serverId/',
    getParentRoute: () => LoggedInLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$serverId': typeof LoggedInLayoutServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$serverId': typeof LoggedInLayoutServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_loggedInLayout': typeof LoggedInLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_loggedInLayout/$serverId/': typeof LoggedInLayoutServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$serverId'
  id:
    | '__root__'
    | '/'
    | '/_loggedInLayout'
    | '/login'
    | '/_loggedInLayout/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggedInLayoutRoute: typeof LoggedInLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loggedInLayout': {
      id: '/_loggedInLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoggedInLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loggedInLayout/$serverId/': {
      id: '/_loggedInLayout/$serverId/'
      path: '/$serverId'
      fullPath: '/$serverId'
      preLoaderRoute: typeof LoggedInLayoutServerIdIndexRouteImport
      parentRoute: typeof LoggedInLayoutRoute
    }
  }
}

interface LoggedInLayoutRouteChildren {
  LoggedInLayoutServerIdIndexRoute: typeof LoggedInLayoutServerIdIndexRoute
}

const LoggedInLayoutRouteChildren: LoggedInLayoutRouteChildren = {
  LoggedInLayoutServerIdIndexRoute: LoggedInLayoutServerIdIndexRoute,
}

const LoggedInLayoutRouteWithChildren = LoggedInLayoutRoute._addFileChildren(
  LoggedInLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggedInLayoutRoute: LoggedInLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
