name: PR Checks Services

on:
  pull_request:
    branches:
      - main

jobs:
  pr-changes:
    name: Get affected services
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'services/api/**/*.(go|mod|sum)'
              - 'services/api/.golangci.json'

  run-api-checks:
    name: Run API PR checks
    needs: pr-changes
    if: ${{ needs.pr-changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Lint API
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3
          working-directory: services/api
