name: PR Checks Services

on:
  pull_request:
    branches:
      - main

jobs:
  pr-changes:
    name: Get affected services
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      bot: ${{ steps.filter.outputs.bot }}
      webClient: ${{ steps.filter.outputs.webClient }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'services/api/**/*.(go|mod|sum)'
              - 'services/api/.golangci.json'
            bot:
              - 'services/bot/**/*.(ts|json)'
              - 'services/bot/.prettierrc'
            webClient:
              - 'services/web-client/*.(json|html|js|ts)'
              - 'services/web-client/src/**'
              - 'services/web-client/public/**'
              - 'services/web-client/.prettierrc'

  run-api-checks:
    name: Run API PR checks
    needs: pr-changes
    if: ${{ needs.pr-changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Lint API
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3
          working-directory: services/api

  run-bot-checks:
    name: Run Bot PR checks
    needs: pr-changes
    if: ${{ needs.pr-changes.outputs.bot == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/bot
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.20"
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies
        run: npm ci
      - name: Lint bot
        run: npm run format:check

  run-web-client-checks:
    name: Run web client PR checks
    needs: pr-changes
    if: ${{ needs.pr-changes.outputs.webClient == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/web-client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19"
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies
        run: npm ci
      - name: Lint web client
        run: npm run format:check
